import { OpenAPIHono } from '@hono/zod-openapi';
import type { AppEnv } from '../../../core/types';
import { authMiddleware } from '../../middlewares/auth';
import { workspaceMiddleware } from '../../middlewares/workspace';
import { auditMiddleware } from '../../middlewares/audit';
import { rateLimitMiddleware } from '../../middlewares/rate-limit';
import { AgentsRoutes } from '../../../modules/agents';
import { ToolsRoutes } from '../../../modules/tools';
import { SkillsRoutes } from '../../../modules/skills';
import { TasksRoutes } from '../../../modules/tasks';
import { CollaborationRoutes } from '../../../modules/collaboration/collaboration.routes';
import { WorkflowRoutes } from '../../../modules/workflows/workflows.routes';
import { sessionsRoutes } from '../../../modules/sessions/sessions.routes';
import { memoryRoutes } from '../../../modules/memory/memory.routes';
import { orchestrationRoutes } from '../../../modules/orchestration/orchestration.routes';
import { agentRegistryRoutes } from '../../../modules/agent-registry/agent-registry.routes';
import { mcpRoutes } from '../../../modules/mcp/mcp.routes';
import { workspaceSettingsRoutes } from '../../../modules/settings/workspace-settings/workspace-settings.routes';
import { ApiKeysRoutes } from '../../../modules/api-keys';
import { usageRoutes } from '../../../modules/usage/usage.routes';
import { FeatureFlagsRoutes } from '../../../modules/feature-flags/feature-flags.routes';
import { MembersRoutes } from '../../../modules/members';
import { BillingRoutes } from '../../../modules/billing/billing.routes';
import { NotificationsRoutes } from '../../../modules/notifications/notifications.routes';
import { CredentialsRoutes } from '../../../modules/credentials/credentials.routes';
import { AuditLogsRoutes } from '../../../modules/audit-logs/audit-logs.routes';
import { InboxRoutes } from '../../../modules/inbox/inbox.routes';
import { PromptsRoutes } from '../../../modules/prompts/prompts.routes';
import { pluginRoutes } from '../../../modules/plugins/plugins.routes';
import { executionRoutes } from '../../../modules/execution/execution.routes';
import { webhooksRoutes } from '../../../modules/webhooks/webhooks.routes';
import { alertRulesRoutes } from '../../../modules/alert-rules/alert-rules.routes';
import { learningRoutes } from '../../../modules/learning/learning.routes';
import { approvalsRoutes } from '../../../modules/approvals/approvals.routes';
import { collabIntelRoutes } from '../../../modules/collab-intel';
import { CommandsRoutes } from '../../../modules/commands/commands.routes';

const workspaceRoutes = new OpenAPIHono<AppEnv>();

// All workspace routes require auth + workspace context + audit + rate limiting
workspaceRoutes.use('*', authMiddleware);
workspaceRoutes.use('*', workspaceMiddleware);
workspaceRoutes.use('*', auditMiddleware);
workspaceRoutes.use('*', rateLimitMiddleware);

// Mount module routes
workspaceRoutes.route('/agents', AgentsRoutes);
workspaceRoutes.route('/tools', ToolsRoutes);
workspaceRoutes.route('/skills', SkillsRoutes);
workspaceRoutes.route('/tasks', TasksRoutes);
workspaceRoutes.route('/collaboration', CollaborationRoutes);
workspaceRoutes.route('/workflows', WorkflowRoutes);
workspaceRoutes.route('/sessions', sessionsRoutes);
workspaceRoutes.route('/memory', memoryRoutes);
workspaceRoutes.route('/orchestrations', orchestrationRoutes);
workspaceRoutes.route('/agent-registry', agentRegistryRoutes);
workspaceRoutes.route('/mcp', mcpRoutes);
workspaceRoutes.route('/settings', workspaceSettingsRoutes);
workspaceRoutes.route('/api-keys', ApiKeysRoutes);
workspaceRoutes.route('/usage', usageRoutes);
workspaceRoutes.route('/feature-flags', FeatureFlagsRoutes);
workspaceRoutes.route('/members', MembersRoutes);
workspaceRoutes.route('/billing', BillingRoutes);
workspaceRoutes.route('/notifications', NotificationsRoutes);
workspaceRoutes.route('/credentials', CredentialsRoutes);
workspaceRoutes.route('/audit-logs', AuditLogsRoutes);
workspaceRoutes.route('/inbox', InboxRoutes);
workspaceRoutes.route('/prompts', PromptsRoutes);
workspaceRoutes.route('/plugins', pluginRoutes);
workspaceRoutes.route('/plans', executionRoutes);
workspaceRoutes.route('/webhooks', webhooksRoutes);
workspaceRoutes.route('/alert-rules', alertRulesRoutes);
workspaceRoutes.route('/learning', learningRoutes());
workspaceRoutes.route('/approvals', approvalsRoutes);
workspaceRoutes.route('/collab-intel', collabIntelRoutes);
workspaceRoutes.route('/commands', CommandsRoutes);

export { workspaceRoutes };
