/**
 * Generates a static tools manifest from the current skill registry.
 * Run: bun run scripts/gen-tools-manifest.ts
 *
 * Updates sdk/tool-definitions.ts with current builtin skills
 * so consumers get type-safe SkillId and static toolDefinitions.
 */
import { BuiltinSkillProvider } from '../src/modules/skills/providers/builtin.provider';

async function main() {
  const provider = new BuiltinSkillProvider();
  const skills = await provider.loadSkills();

  const names = skills.map((s) => `'${s.name}'`).join(' | ');
  const defs = skills
    .map(
      (s) =>
        `  { name: '${s.name}', description: '${s.description.replace(/'/g, "\\'")}', inputSchema: ${JSON.stringify(s.inputSchema)} },`,
    )
    .join('\n');

  const output = `// AUTO-GENERATED by scripts/gen-tools-manifest.ts — do not edit manually
import { skillRegistry } from '../modules/skills/skills.registry';
import type { ToolInfo } from './types';

/** Live snapshot of currently registered tools */
export function getToolDefinitions(): ToolInfo[] {
  return skillRegistry.list().map((s) => ({
    name: s.name,
    description: s.description,
    inputSchema: s.inputSchema,
  }));
}

/** Static well-known tool names — updated by codegen script */
export type SkillId = ${names} | (string & {});

/** For consumers that need a flat array at import time */
export const toolDefinitions: ToolInfo[] = [
${defs}
];
`;

  const path = new URL('../src/sdk/tool-definitions.ts', import.meta.url).pathname;
  const filePath = path.startsWith('/') && path[2] === ':' ? path.slice(1) : path;
  await Bun.write(filePath, output);
  console.log(`Generated ${filePath} with ${skills.length} tools`);
}

main().catch(console.error);
